import os

file_path = r"d:\workspaces\davis\ai-code-analyzer\client\src\pages\Analysis.tsx"

with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Find the start of the Stop Confirmation Modal
start_index = -1
for i, line in enumerate(lines):
    if "{/* Stop Confirmation Modal */}" in line:
        start_index = i
        break

if start_index == -1:
    print("Could not find Stop Confirmation Modal start")
    exit(1)

# Keep lines before the modal
new_content = lines[:start_index]

# Append the correct content
new_content.append("            {/* Stop Confirmation Modal */}\n")
new_content.append("            {showStopConfirmModal && (\n")
new_content.append("                <div className=\"fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in duration-200\">\n")
new_content.append("                    <div className=\"bg-white rounded-2xl shadow-2xl w-full max-w-md overflow-hidden animate-in zoom-in-95 duration-200 border border-slate-100\">\n")
new_content.append("                        <div className=\"p-8\">\n")
new_content.append("                            <div className=\"flex flex-col items-center text-center\">\n")
new_content.append("                                <div className=\"w-16 h-16 bg-rose-50 rounded-full flex items-center justify-center mb-6 ring-8 ring-rose-50/50\">\n")
new_content.append("                                    <Square className=\"w-8 h-8 text-rose-500 fill-current\" />\n")
new_content.append("                                </div>\n")
new_content.append("\n")
new_content.append("                                <h3 className=\"text-xl font-bold text-slate-900 mb-3\">\n")
new_content.append("                                    {t('analysis.analysisStopConfirmTitle')}\n")
new_content.append("                                </h3>\n")
new_content.append("\n")
new_content.append("                                <p className=\"text-slate-500 whitespace-pre-wrap leading-relaxed mb-8\">\n")
new_content.append("                                    {t('analysis.analysisStopConfirmMessage')}\n")
new_content.append("                                </p>\n")
new_content.append("\n")
new_content.append("                                <div className=\"flex gap-3 w-full\">\n")
new_content.append("                                    <button\n")
new_content.append("                                        type=\"button\"\n")
new_content.append("                                        className=\"flex-1 py-3 px-4 bg-white border border-slate-200 text-slate-700 font-semibold rounded-xl hover:bg-slate-50 hover:border-slate-300 transition-all active:scale-[0.98]\"\n")
new_content.append("                                        onClick={() => setShowStopConfirmModal(false)}\n")
new_content.append("                                    >\n")
new_content.append("                                        {t('common.cancel')}\n")
new_content.append("                                    </button>\n")
new_content.append("                                    <button\n")
new_content.append("                                        type=\"button\"\n")
new_content.append("                                        className=\"flex-1 py-3 px-4 bg-rose-600 text-white font-semibold rounded-xl shadow-lg shadow-rose-200 hover:bg-rose-700 hover:shadow-rose-300 transition-all active:scale-[0.98]\"\n")
new_content.append("                                        onClick={executeStopAnalysis}\n")
new_content.append("                                    >\n")
new_content.append("                                        {t('analysis.confirm')}\n")
new_content.append("                                    </button>\n")
new_content.append("                                </div>\n")
new_content.append("                            </div>\n")
new_content.append("                        </div>\n")
new_content.append("                    </div>\n")
new_content.append("                </div>\n")
new_content.append("            )}\n")
new_content.append("\n")
new_content.append("            {/* Status Panel */}\n")
new_content.append("            <div className=\"bg-white rounded-2xl shadow-sm border border-slate-100 p-6\">\n")
new_content.append("                <h3 className=\"text-lg font-bold text-slate-900 mb-4 flex items-center gap-2\">\n")
new_content.append("                    <ActivityIcon className=\"w-5 h-5 text-indigo-600\" />\n")
new_content.append("                    {t('analysis.analysisStatus')}\n")
new_content.append("                </h3>\n")
new_content.append("\n")
new_content.append("                {\n")
new_content.append("                    jobId ? (\n")
new_content.append("                        <div className=\"space-y-4\">\n")
new_content.append("                            <div className=\"grid grid-cols-1 md:grid-cols-2 gap-4\">\n")
new_content.append("                                <div className=\"p-4 bg-slate-50 rounded-xl border border-slate-100\">\n")
new_content.append("                                    <div className=\"text-xs text-slate-500 uppercase tracking-wider font-semibold mb-1\">{t('analysis.jobId')}</div>\n")
new_content.append("                                    <div className=\"font-mono text-sm text-slate-700 break-all\">{jobId}</div>\n")
new_content.append("                                </div>\n")
new_content.append("\n")
new_content.append("                                <div className=\"flex items-center gap-3 p-4 bg-indigo-50 rounded-xl border border-indigo-100\">\n")
new_content.append("                                    {status === 'completed' ? (\n")
new_content.append("                                        <CheckCircle className=\"w-5 h-5 text-emerald-500\" />\n")
new_content.append("                                    ) : status === 'failed' ? (\n")
new_content.append("                                        <AlertCircle className=\"w-5 h-5 text-red-500\" />\n")
new_content.append("                                    ) : status === 'canceled' || status === 'cancelled' || status === 'cancelling' ? (\n")
new_content.append("                                        <XCircle className=\"w-5 h-5 text-slate-500\" />\n")
new_content.append("                                    ) : (\n")
new_content.append("                                        <Loader2 className=\"w-5 h-5 text-indigo-500 animate-spin\" />\n")
new_content.append("                                    )}\n")
new_content.append("                                    <div>\n")
new_content.append("                                        <div className=\"text-xs text-indigo-600 uppercase tracking-wider font-semibold\">{t('analysis.currentStatus')}</div>\n")
new_content.append("                                        <div className=\"font-bold text-indigo-900 capitalize\">{status || 'Pending...'}</div>\n")
new_content.append("                                    </div>\n")
new_content.append("                                </div>\n")
new_content.append("                            </div>\n")
new_content.append("\n")
new_content.append("                            {/* Progress Bar */}\n")
new_content.append("                            {(status === 'running' || status === 'pending' || status === 'cancelling') && progress && (\n")
new_content.append("                                <div className=\"w-full bg-white p-4 rounded-xl border border-slate-200 shadow-sm\">\n")
new_content.append("                                    <div className=\"flex justify-between text-xs text-slate-600 mb-2 font-medium\">\n")
new_content.append("                                        <div className=\"flex items-center gap-2\">\n")
new_content.append("                                            <Loader2 className=\"w-3 h-3 animate-spin text-indigo-600\" />\n")
new_content.append("                                            <span>Processing... {progress.current}/{progress.total}</span>\n")
new_content.append("                                        </div>\n")
new_content.append("                                        <span className=\"text-indigo-600 font-bold\">{progress.percent}%</span>\n")
new_content.append("                                    </div>\n")
new_content.append("                                    <div className=\"w-full bg-slate-100 rounded-full h-2 overflow-hidden\">\n")
new_content.append("                                        <div\n")
new_content.append("                                            className=\"bg-indigo-600 h-2 rounded-full transition-all duration-500 ease-out shadow-[0_0_10px_rgba(79,70,229,0.3)]\"\n")
new_content.append("                                            style={{ width: `${progress.percent}%` }}\n")
new_content.append("                                        ></div>\n")
new_content.append("                                    </div>\n")
new_content.append("                                    <div className=\"mt-2 text-[10px] text-slate-400 truncate font-mono\">\n")
new_content.append("                                        {progress.raw}\n")
new_content.append("                                    </div>\n")
new_content.append("                                </div>\n")
new_content.append("                            )}\n")
new_content.append("\n")
new_content.append("                            {/* Log Actions */}\n")
new_content.append("                            <div className=\"flex gap-3 pt-2\">\n")
new_content.append("                                <button\n")
new_content.append("                                    onClick={() => setShowLogModal(true)}\n")
new_content.append("                                    className=\"flex-1 flex items-center justify-center gap-2 py-2.5 px-4 bg-white border border-slate-200 text-slate-700 rounded-xl hover:bg-slate-50 hover:text-indigo-600 transition-colors text-sm font-medium shadow-sm\"\n")
new_content.append("                                >\n")
new_content.append("                                    <FileText className=\"w-4 h-4\" />\n")
new_content.append("                                    {t('analysis.viewLogs')}\n")
new_content.append("                                </button>\n")
new_content.append("                                <button\n")
new_content.append("                                    onClick={() => setShowSummaryModal(true)}\n")
new_content.append("                                    disabled={status !== 'completed'}\n")
new_content.append("                                    className={`flex-1 flex items-center justify-center gap-2 py-2.5 px-4 rounded-xl transition-all text-sm font-medium shadow-md ${status === 'completed'\n")
new_content.append("                                        ? 'bg-indigo-600 text-white hover:bg-indigo-700 shadow-indigo-200'\n")
new_content.append("                                        : 'bg-slate-100 text-slate-400 cursor-not-allowed shadow-none'\n")
new_content.append("                                        }`}\n")
new_content.append("                                >\n")
new_content.append("                                    <List className=\"w-4 h-4\" />\n")
new_content.append("                                    {t('analysis.viewResultSummary')}\n")
new_content.append("                                </button>\n")
new_content.append("                            </div>\n")
new_content.append("                        </div>\n")
new_content.append("                    ) : (\n")
new_content.append("                        <div className=\"text-center py-8 text-slate-400\">\n")
new_content.append("                            <FileCode className=\"w-12 h-12 mx-auto mb-3 opacity-20\" />\n")
new_content.append("                            <p className=\"text-sm\">{t('analysis.noAnalysisRunning')}</p>\n")
new_content.append("                        </div>\n")
new_content.append("                    )\n")
new_content.append("                }\n")
new_content.append("            </div>\n")
new_content.append("        </div>\n")
new_content.append("\n")
new_content.append("    );\n")
new_content.append("};\n")
new_content.append("\n")
new_content.append("export default Analysis;\n")

with open(file_path, 'w', encoding='utf-8') as f:
    f.writelines(new_content)

print("Successfully fixed Analysis.tsx")
