from __future__ import annotations
from pydantic import BaseModel, model_validator
from typing import Any, Literal
from .base import Annotation

class Field(BaseModel):
    """Represents a field or property within a class."""

    name: str
    logical_name: str = ""
    type: str
    modifiers: list[str] = []
    package_name: str = ""
    class_name: str = ""
    annotations: list[Annotation] = []
    initial_value: str = ""  # Initial value of the field
    description: str = ""  # Brief description of the field
    ai_description: str = ""  # AI-generated description of the field
    bxm_field_attrs: dict[str, Any] = {}  # Bxm Framework: @BxmOmm_Field 속성


class Method(BaseModel):
    """Represents a method within a class."""

    name: str
    logical_name: str = ""
    return_type: str
    parameters: list[Field] = []
    modifiers: list[str] = []
    source: str = ""
    metadata: str = ""
    package_name: str = ""
    annotations: list[Annotation] = []
    description: str = ""  # Brief description of the method
    ai_description: str = ""  # AI-generated description of the method
    is_lombok_generated: bool = False  # Flag to indicate if method is generated by Lombok
    calls: list[str] = []  # List of method calls made by this method

    # LOC 메트릭
    PLOC: int = 0  # Physical LOC (물리적 LOC): 메서드 내 모든 라인의 수
    LLOC: int = 0  # Logical LOC (논리적 LOC): 메서드 내 실제 실행 가능한 구문 라인수, 주석 라인과 공백 라인 제외
    CLOC: int = 0  # Comment LOC (주석 LOC): 메서드 내 주석으로만 이루어진 라인의 수

    # 복잡도 메트릭
    cognitive_complexity: int = 0  # Cognitive Complexity: 코드가 사람이 이해하고 유지보수하기에 얼마나 어려운지를 측정하는 지표 (SonarSource)


class MethodCall(BaseModel):
    """Represents a method call from one method to another."""

    source_package: str
    source_class: str
    source_method: str
    target_package: str
    target_class: str
    target_method: str
    call_order: int = 0  # 순서 정보 (0부터 시작)
    line_number: int = 0  # 소스 코드에서의 라인 번호
    return_type: str = "void"  # 피호출 메서드의 return type
    description: str = ""  # Brief description of the method call
    ai_description: str = ""  # AI-generated description of the method call

    def dict(self):
        """Convert to dictionary for JSON serialization."""
        return {
            "source_package": self.source_package,
            "source_class": self.source_class,
            "source_method": self.source_method,
            "target_package": self.target_package,
            "target_class": self.target_class,
            "target_method": self.target_method,
            "call_order": self.call_order,
            "line_number": self.line_number,
            "return_type": self.return_type
        }


class Class(BaseModel):
    """Represents a Java class with its methods, properties, and relationships."""

    name: str
    logical_name: str = ""
    file_path: str
    file_extension: str = ""
    type: Literal["class", "interface", "enum"] = "class"
    sub_type: str = ""  # controller, service, util, dto, config, mapper, repository, entity, exception, client
    methods: list[Method] = []
    properties: list[Field] = []
    calls: list[MethodCall] = []
    source: str = ""
    source_hashcode: str = ""
    superclass: str | None = None
    interfaces: list[str] = []
    imports: list[str] = []
    annotations: list[Annotation] = []
    package_name: str = ""
    description: str = ""  # Brief description of the class
    ai_description: str = ""  # AI-generated description of the class
    bxm_category: str = ""  # Bxm Framework: @BxmCategory logicalName 값

    # LOC 메트릭
    PLOC: int = 0  # Physical LOC (물리적 LOC): 파일에 있는 모든 라인의 수
    LLOC: int = 0  # Logical LOC (논리적 LOC): 실제 실행 가능한 구문 라인수, 주석 라인과 공백 라인 제외
    CLOC: int = 0  # Comment LOC (주석 LOC): 주석으로만 이루어진 라인의 수

    # 복잡도 메트릭
    code_complexity: int = 0  # Code Complexity: Java 코드의 라인수, 필드, 메서드 수 등 분석 및 유지보수 하기 어려운 정도를 수치화
                              # 계산식: lines*1 + fields*2 + methods*5 + inner_classes*10 + annotations*1

    @model_validator(mode="before")
    @classmethod
    def populate_package_name(cls, values):
        if isinstance(values, dict):
            package = values.pop("package", None)
            if package and not values.get("package_name"):
                values["package_name"] = package
        return values

    @property
    def package(self) -> str:
        """기존 코드 호환을 위해 package 속성을 package_name과 동기화한다."""
        return self.package_name

    @package.setter
    def package(self, value: str) -> None:
        """package 속성에 값을 넣으면 내부적으로 package_name에 반영한다."""
        self.package_name = value
